### ISSUE TITLE
Contact page alignment - browser mode

### ISSUE THREAD

**Issue by AngeleLifeGiver** [mpaqman/great-peace-org#2]
1- alignment between header, first picture, and the text:
![image](https://user-images.githubusercontent.com/117110982/199074570-5d817471-b266-4d93-b67e-b18af912b4e0.png)
You can see the birds are larger than the rest

2- Marie-Claude's picture is too wide on the right side, it gets on the section beside it.
![image](https://user-images.githubusercontent.com/117110982/199074975-af8a9949-5a16-4cc7-bc07-4a18b5c4ebad.png)

3- Two Row Wampum image is too wide on the right side to fit the section where it is:
![image](https://user-images.githubusercontent.com/117110982/199074779-e4f25985-480e-4dba-88e8-17e7bf5ed9b8.png)

**Comment by AngeleLifeGiver** [comment]
@mpaqman planning on adjusting it when???? it's been 15 days already...

**Comment by mpaqman** [comment]
I'm marking this issue as resolved by pull request #4. Thank you for your patience @AngeleLifeGiver sorry for the really excessive wait. It will be faster next time.
