### ISSUE TITLE
Contribute button - contribute page

### ISSUE THREAD

**Issue by AngeleLifeGiver** [mpaqman/great-peace-org#5]
The paypal link doesn't work & we would need it to work to facilitate donations, ideally shortly, just in case.
If you have other ideas? I didn't research on paypal business account, if you need me to do it let me know

**Comment by AngeleLifeGiver** [comment]
Found this on google:
https://www.paypal.com/us/cshelp/article/HELP259?locale.x=en_US

**Comment by AngeleLifeGiver** [comment]
This one better, donations button:
https://www.paypal.com/ca/webapps/mpp/non-profits/fundraising/donate-button

**Comment by mpaqman** [comment]
Closed with PR #9
