### ISSUE TITLE
Bio modification - Angele - Contact Page - English

### ISSUE THREAD

**Issue by AngeleLifeGiver** [mpaqman/great-peace-org#6]
Please change the text for Angele to this instead:
Angèle Pelletier
Founding Member

I graduated as a management accountant in 2004 from Laval University and have been a chartered management accountant (CPA, CMA) for 16 years. I have also been an IT management solution specialist and project manager since 2010.
Aware of the impact of corporations too often destructive on the environment, I fiercely wished to reconcile my work with my desire to transform our world for the better.
Having been exposed to key and empowering truths of Native Teachings, I identified many concrete solutions for action.
It is with this certainty that I helped found the Great Peace Organization which for me is the essential missing link for the reconnection to the sacred.
"Let us be the change we want to see in the world."

**Comment by mpaqman** [comment]
Closing this issue as it was resolved by PR #8
