### ISSUE TITLE
Modification bio - Angele - contact page - French

### ISSUE THREAD

**Issue by AngeleLifeGiver** [mpaqman/great-peace-org#7]
Please modify the text for this instead:
Angèle Pelletier
Membre fondatrice

J'ai gradué en tant que comptable en Management en 2004 à l'Université Laval et j'ai été accréditée (CPA, CMA) pendant 16 ans.
Je suis également spécialiste dans l'implantation de systèmes intégrés et gestionnaire de projets depuis 2010.
Consciente de l'impact des corporations trop souvent négatif sur l'environnement, je souhaitais ardemment réconcilier mon travail avec mon désir de transformer notre monde pour le mieux.
Ayant été exposée à des enseignements autochtones clés et désarmants de vérité, j'ai identifié plusieurs solutions concrètes d'action.
C'est avec cette certitude que j'ai participé à la fondation de l'Organisation de la Grande Paix, qui pour moi représente le chaînon essentiel manquant pour la reconnection au sacré.

"Soyons le changement que nous souhaitons voir dans le monde."

**Comment by mpaqman** [comment]
Closing this issue as it was resolved by PR #8
